server:
  port: 10010
spring:
  application:
    name: client-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    search-service: /search/** # 将搜索微服务映射到/search/**
    user-service: /user/** # 将用户微服务映射到/user/**
    auth-service: /auth/** # 将授权中心微服务映射到/auth/**
    cart-service: /cart/** # 将购物车微服务映射到/auth/**
    order-service: /order/** # 将购物车微服务映射到/auth/**



  add-host-header: true  #携带请求本省host头信息
  sensitive-headers:    #把敏感头设置为null
  ignored-services: upload-service  # 忽略upload-service服务
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
ly:
  jwt:
    pubKeyPath: F:/heima/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/code
    - /api/item